<ResizeWidget@Widget>:
    size_hint_y: None

<ResizableSpan@ResizeWidget+Label>:
#    size_hint_y: None
    height: self.texture_size[1]

<TextField@ResizeWidget+TextInput>:
#    size_hint_y: None
    height: dp(30)

<PrimaryButton@ResizeWidget+Button>:
    size_hint_x: None
    size: self.texture_size[0], dp(30)
    valign: 'middle'
    halign: 'center'
    font_size: '16sp'
    padding: '10sp', '4sp'
