name: Specs

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  specs:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pyobjc-core pyobjc python3-xlib -r requirements.txt
      - name: Install Additional Linux Dependencies
        run: |
          apt-get update
          apt-get install -y scrot python3-tk
      - name: Run Tests
        run: |
          python -m pytest --disable-warnings
